wands:
  fire:
    color: c
    item: blaze_rod
    customname: '&4Fire Wand'
  ice:
    color: 3
    item: bone
    customname: '&bIce Wand'
  nature:
    color: a
    item: bamboo
    customname: '&aNature Wand'
  flower:
    color: d
    item: poppy
    customname: '&dHanamura Flower Wand'
spells:
  fireleap:
    playercooldown: 15
    staffcooldown: 0
  firepulse:
    damage: 5